services:
  database:
    image: postgres
    restart: always
    container_name: academy_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: platform_db
    volumes:
      - db:/data/postgres
    ports:
      - 5432:5432

volumes:
  db: