"""Set a nullable field for course.certid

Revision ID: 156afc10bc16
Revises: 7e4285de9c10
Create Date: 2025-03-11 16:10:01.550157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156afc10bc16'
down_revision: Union[str, None] = '7e4285de9c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'cert_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('job_listing', sa.Column('pay', sa.Integer(), nullable=False))
    op.drop_column('job_listing', 'monthly_salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listing', sa.Column('monthly_salary', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('job_listing', 'pay')
    op.alter_column('course', 'cert_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
