"""Changed job_listing pay -> monthly salary

Revision ID: 20a048b20f24
Revises: e1dd9891e766
Create Date: 2025-03-11 18:30:11.719384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a048b20f24'
down_revision: Union[str, None] = 'e1dd9891e766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listing', sa.Column('monthly_salary', sa.Integer(), nullable=False))
    op.drop_column('job_listing', 'pay')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listing', sa.Column('pay', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('job_listing', 'monthly_salary')
    # ### end Alembic commands ###
