"""Joel test migration

Revision ID: 570d25698500
Revises: 
Create Date: 2025-03-08 23:47:13.411920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570d25698500'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('cert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('question_paper', sa.JSON(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cleared', sa.Boolean(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earned_marks', sa.Float(), nullable=True),
    sa.Column('attempted_on', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('application', sa.Column('status', sa.String(length=255), nullable=False))
    op.add_column('certificate', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'certificate', 'course', ['course_id'], ['id'])
    op.add_column('job_listing', sa.Column('monthly_salary', sa.Integer(), nullable=True))
    op.add_column('user_cert', sa.Column('additional_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_cert', 'additional_info')
    op.drop_column('job_listing', 'monthly_salary')
    op.drop_constraint(None, 'certificate', type_='foreignkey')
    op.drop_column('certificate', 'course_id')
    op.drop_column('application', 'status')
    op.drop_table('assessment_attempt')
    op.drop_table('course_progress')
    op.drop_table('assessment')
    op.drop_table('course')
    # ### end Alembic commands ###
