"""joel new job migration

Revision ID: 7e4285de9c10
Revises: 6bfbe538f7b0
Create Date: 2025-03-11 00:27:39.711069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4285de9c10'
down_revision: Union[str, None] = '6bfbe538f7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_listing', 'pay')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listing', sa.Column('pay', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
