"""Changed certificate valid period to an integer of years

Revision ID: e1dd9891e766
Revises: 156afc10bc16
Create Date: 2025-03-11 18:05:24.294790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1dd9891e766'
down_revision: Union[str, None] = '156afc10bc16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('years_valid', sa.Integer(), nullable=True))
    op.alter_column('certificate', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('certificate', 'validity_period')
    op.alter_column('course', 'cert_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'cert_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('certificate', sa.Column('validity_period', postgresql.TIME(), autoincrement=False, nullable=False))
    op.alter_column('certificate', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('certificate', 'years_valid')
    # ### end Alembic commands ###
